[package]
name = "procrastinate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive"] }
file-lock = "2.1.11"
nom = "7.1.3"
ron = "0.8.1"
serde = { version = "1.0.199", features = ["derive"] }

[[bin]]
name = "procrastinate"

